### ISSUE TITLE
Create nice readme and check licence

### ISSUE THREAD

**Issue by landgenoot** [digital-voting-pass/digital-voting-pass-app#106]

**Comment by klikooo** [comment]
`bitcoinj` has: Apache License 2.0
`Multichain` has GPL v3
`JMRTD` has  LGPL v3
`Tesseract` has Apache License 2.0
`CryptoPP` = Crypto++ Library is copyrighted as a compilation and (as of version 5.6.2) licensed under the Boost Software License 1.0, while the individual files in the compilation are all public domain.

**Comment by landgenoot** [comment]
![ezgif-3-98449bd2bd](https://user-images.githubusercontent.com/2787511/27002571-8d902bb8-4de5-11e7-94d5-da48a4209fdc.gif)
For hosting as githubusercontent

**Comment by landgenoot** [comment]
Github free image hosting...

![3-11](https://user-images.githubusercontent.com/2787511/27711362-6362315e-5d23-11e7-9275-f410206e73f2.png)
![3-10](https://user-images.githubusercontent.com/2787511/27711360-6360bce8-5d23-11e7-9653-5075637a1d0b.png)
![3-9](https://user-images.githubusercontent.com/2787511/27711361-6361f540-5d23-11e7-80c3-95307bf43ad5.png)
![3-8](https://user-images.githubusercontent.com/2787511/27711364-636916e0-5d23-11e7-8428-48aea50e2afb.png)
![3-7](https://user-images.githubusercontent.com/2787511/27711365-63699ed0-5d23-11e7-82c1-975a5c2e43cb.png)
![3-6](https://user-images.githubusercontent.com/2787511/27711363-6363a728-5d23-11e7-904a-82618d04e923.png)
![3-5](https://user-images.githubusercontent.com/2787511/27711366-6374e6be-5d23-11e7-9046-5937a373965a.png)
![3-4](https://user-images.githubusercontent.com/2787511/27711368-63791de2-5d23-11e7-9c71-ba5a2cdc27e4.png)
![3-3](https://user-images.githubusercontent.com/2787511/27711367-63762600-5d23-11e7-9895-4a069ad9d619.png)
![3-2](https://user-images.githubusercontent.com/2787511/27711369-6379749a-5d23-11e7-99f7-ba2d1c33018b.png)
![3-1](https://user-images.githubusercontent.com/2787511/27711371-6381799c-5d23-11e7-8b12-6b3b1fb53ea2.png)
![2-6](https://user-images.githubusercontent.com/2787511/27711370-63800e90-5d23-11e7-9cc3-a4bcefaba248.png)
![2-5](https://user-images.githubusercontent.com/2787511/27711373-638f68fe-5d23-11e7-8e07-d7dd0f3bb2fd.png)
![2-4](https://user-images.githubusercontent.com/2787511/27711372-638b5796-5d23-11e7-9c92-abc53ff32958.png)
![2-3](https://user-images.githubusercontent.com/2787511/27711374-6391db20-5d23-11e7-9d7c-dc1b01baba39.png)
![2-2](https://user-images.githubusercontent.com/2787511/27711375-6392b644-5d23-11e7-85fa-77f68cb0c5d1.png)
![2-1](https://user-images.githubusercontent.com/2787511/27711376-639d83da-5d23-11e7-8ccb-538ba37103b1.png)
![1-12](https://user-images.githubusercontent.com/2787511/27711378-63a43504-5d23-11e7-87af-aea1749852a8.png)
![1-11](https://user-images.githubusercontent.com/2787511/27711377-639f6d4e-5d23-11e7-8a2b-e918f4ef5ac2.png)
![1-10](https://user-images.githubusercontent.com/2787511/27711380-63a956a6-5d23-11e7-96b4-4799f6a90c2f.png)
![1-9](https://user-images.githubusercontent.com/2787511/27711379-63a61018-5d23-11e7-9c00-cfc1b89de3b9.png)
![1-8](https://user-images.githubusercontent.com/2787511/27711381-63ac1ba2-5d23-11e7-90e8-ae1fa73ce11b.png)
![1-7](https://user-images.githubusercontent.com/2787511/27711382-63b32ca8-5d23-11e7-8c2b-66bfa237998e.png)
![1-6](https://user-images.githubusercontent.com/2787511/27711383-63bafa0a-5d23-11e7-8b61-ddfa5c7df3de.png)
![1-5](https://user-images.githubusercontent.com/2787511/27711384-63bbd31c-5d23-11e7-9e0d-92c58ab7f08c.png)
![1-4](https://user-images.githubusercontent.com/2787511/27711385-63bccf7e-5d23-11e7-8629-77a73937aae2.png)
![1-3](https://user-images.githubusercontent.com/2787511/27711387-63c2f2dc-5d23-11e7-873b-895562cd0268.png)
![1-2](https://user-images.githubusercontent.com/2787511/27711386-63c16462-5d23-11e7-96f8-516e35189087.png)
![1-1](https://user-images.githubusercontent.com/2787511/27711388-63c9f4b0-5d23-11e7-8794-3b36eb37a6b5.png)
