### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by klikooo** [digital-voting-pass/digital-voting-pass-app#138]
**Chapters**
- [x] Introduction
  - [x] Process description
  - [x] Project methodology -> goals
- [x] Problem description
  - [x] Needs of client
  - [x] Problem Analysis
  - [x] How do we fix the problem
  - [x] Requirements
- [x] Full prototype
  - [x] MultiChain compatible with travel document
  - [x] How is a transaction build
  - [x] Screenshots?
  - [x] Response from a municipality (if we can get an interview with someone)
- [x] Performance analysis
  - [x] Verifying a single transactions => brainpool vs secp
  - [x] Creating elections
  - [x] How fast is the chain downloaded and processed
  - [x] Size of chain
  - [x] Average waiting time for a transaction
  - [x] Security
       - [x] Description of the key aspects involving security
       - [x] Analysis of security of used concepts 
         - [x] Blockchain
         - [x] Crypto passport
- [x] Quality assurance
  - [x] SIG feedback
      - [x] Explain why not all libraries where fully uploaded (see [comment Pouwelse](https://github.com/Tribler/tribler/issues/2918) June 14th)
      - [x] How did we address the feedback?
      - [x] Sig II feedback (when on time, otherwise just add to the version that gets uploaded to the repository)
  - [x] Multichain tests
  - [x] Other tests
- [x] Societal impact
  - [x] Political response
  - [x] Required legislative changes
  - [x] Trust in the system
  - [x] Positive and negative changes for voters
- [x] Summary
- [x] Conclusion & Discussion
  - [x] Encountered difficulties
- [x]	Further improvements:
  - [x] Scanning of face and check with picture of travel document
  - [x] Proxy voting (maybe)
    - [x] Enforce max 3 ballots in blockchain
  - [x] Don't specify with which document you want to vote, just you want to vote digital
  - [x] Multisig with government priv key to retract voting rights
  - [x] voting with drivers license
  - [x] Use the metadata capabilites of MultiChain and store a password, so a voter can redeem its voting right with an ID and a password

**Other**
- [x] UX implementation [W]
  - [x] Link with trust (blue is peaceful/trustworthy)
- [x] Add UML diagrams
- [x] Node organization
- [x] Clear description of what the difference is between a public key and address
- [x] Influence in other problems which require ID
- [x] Infosheet	as	an	appendix
- [x] reference to original problem description and how our solution differs from it.
- [x] Add a paragraph about the ethical implications. (probably mostly about privacy, stemgeheim etc.)

# From Pouwelse
- [x] MOSCOW pointer sentence in intro + 1 line this is a thesis project.
- [x] blockchain and e-passport prototype (suggestion title for Ch 3)
- [x] fault-tolerance and attack-resilience
  - [x] summary
- [x] thousands votes are lost in the last election.
- [x] with accusations that Russia has electronically attacked US-presential elections..
- [x] easy to read picture for chapter 1 or 2 (illustrate analog voting pass).
- [x] intro : we use the blockchain as a tamper-proof database. ensure integrity
- [x] all appendixes are pointed to and have intro sentence.
- [x] Voting passes from a live blockchain (suggestion title for Ch 4)
- [x] add screenshots to chapters
- [x] chapter 6: MBytes ?
- [x] needs overall polish
- [x] Explain that voter helper app was not implemented

# Main requirements
Requirements	for	the	formal	form	of	the	final	report.	The	report…
- [x] Must	be	well	structured.	Each	section,	sub-section	should	have	a	clear	purpose.	Paragraphs	
should	open	with	a	topic	sentence	and	the	rest	of	the	paragraph	should	support	the	topic.	
- [x] Must	 contain	 at	 least	 6	 sections.	 Sections	 should	 at	 least	 include:	 a	 foreword,	 a	 table	 of	
contents,	a	summary,	an	introduction,	problem	definition	and	problem	analysis,	the	design,	
the	 implementations,	 the	 conclusions,	 discuss	 and	 recommendations,	 a	 conclusion,	 a	
reference	list.	Note	that	different	structures	will	be	more	appropriate	for	different	projects.
- [x] Must	include	 references	 to	 the	 references	 or	 other	 sources	 that	were	analyzed	during	 the	
research	phase.	Please	check	that	your	references	are	properly	and	consistently	formatted.
- [x] Must	be	spell- and	grammar-checked.	Check	that	abbreviations	are	defined	at	their	first	use.	
Check	that	tables	and	figures	are	labeled	with	captions.
- [x] Must	include	a	title	page.	Make	sure	not	to	forget:	name	of	the	members	of	the	team	and	the	
Bachelor	 Project	 Committee	 (Coach,	 Client,	 Bachelor	 Project	 Coordinator).	 Include	 your	
student	number	in	the	email	that	you	send	to	your	Committee,	but	not	in	the	report.
- [x] Must	include	the	Infosheet	as	an	appendix.	(See	below	for	instructions.)
- [x] Must	include	 the	 research	 report	 (10	 pages)	 either	 as	 an	 appendix	 or integrated	into	 the	
report.
- [x] Should	include	the	original	project	description	as	an	appendix.	
- [x] Should	be	30-50	pages	(plus	appendices,	if	necessary).
- [x] Must	include	 the	 first	 feedback	 of	 the	SIG,	 how	 the	 team	addressed	 the	 feedback,	and	 the	
second	feedback	of the	SIG	(if	necessary,	the	second	feedback	of	the	SIG	can	be	added	after	
the	final	presentation	and	before	uploading	the	report	to	http://repository.tudelft.nl)
- [x] The	 report	is	a	public	document.	Proprietary	information	should	be	 kept	 to	 the	minimum	
necessary.	It	should	be	included	in	an	appendix	that	can	be	removed	before	publishing	the	
report	to	http://repository.tudelft.nl

# List of some requirements of report
- [x] Has	the	team	remembered	to	include	a	clear	description	of	the	problem	that	is	addressed	by	the	
project?	Does	the	description	include	mention	of	the	immediate	context	of	the	project,	including	the	
needs	and	the	motivation	of	the	Client?
- [x] Is	the	larger	context	and	vision	of	the	project	described?	What	is	the	potential	impact	on	day-today
business	or	business,	on	people’s	daily	lives,	on	society	at	large?
- [x] Is	the	solution	proposed	by	the	team	clearly	described?
- [x] Is	the	software	development	methodology	chosen	by	the	team	clear	and	well	justified?
10
2017 General	Guide	Computer	Science	Bachelor	Project
- [x] Is	 the	 process	 by	 which	 the	 team	 arrived	 at	its	 solution	 to	 solution	 clearly	 described?	Does	it	
reflect	the	problem	analysis	that	was	carried	out	and	the research	questions	that	were	addressed?	
Does	the	report	include	the	appropriate	references?
- [x] Are	the	requirements	clear?	Do	they	have	an	appropriate	level	of	detail?	Are	they	prioritized?
- [x] Is	 it	 clear	 that	 the	 team	 developed	 success	 criteria,	 i.e.,	 did	 they have	 a	 clear	 picture	 at	 the	
beginning	of	the	project	how	they	would	recognize	success	when	they	achieved	it?	
- [x] Are	 the	 system	 specifications	 complete?	 Do	 they	 reflect	 both	 the	 big	 picture	 and	 the	 details	
needed	for	implementation?	Are	UML	diagrams	used	to	support	understanding	of	the	application?	
Are	they	used	appropriately	(communicate	what	is	essential,	but	also	avoid	redundancy)?
- [x] Does	the	report	include	plans	for	quality	control	and	testing?
- [x] Does	 the	report	allow	 the	reader	 to	understand	how	 the	software development	methodology	
was	applied?	Does	the	report	allow	the	reader	to	understand	the	division	of	labor	among	members	
of	the	team	and	how	the	team	communicated	(both	among	themselves	and	with	the	Coach	and	the	
Client)?
- [x] Did	 the	 team	remember	 to	include	a complete	description	of	 the	 final	product?	(Are	graphics	
used	appropriately	to	this	end?)
- [x] Does	the	report	close	the	loop	(i.e.,	provide	evidence	that	the	initial	problem	was	solved)?
- [x] Does	the	report	include	the	necessary	background	information?	This	should	be	the	information	
needed	by	someone	with	a	technical	background,	but	not	necessarily	one	lying	directly	in	the	field	
of	the	project	to	understand	it?	(Or	think	about	the	more	specific	question,	“Would	the	Dean	be	able	
to	follow	it?”	http://www.ewi.tudelft.nl/en/the-faculty/dean/)
- [x] Is	something	 that	 the	 team	spent	a	lot	of	 time	on	not	mentioned	in	 the	 report?	Did	 the	 team	
make	any	important	decisions	that	do	not	appear	in	the	report?
- [x]  Are	there	important	insights	about	what	the	team	feels	that	they	should	have	done	differently	
in	retrospect	that	are	not	included	in	the	report?
- [x] Does	the	team	have	recommendations	for	the	Client	that	were	not	included	in	the	report?
- [x] Would	this	report	allow	other	similar	teams	to	understand	what	was	done,	in	order	to	extend	
this	project	or	to	create	a	similar	one?
- [x] Does	the	report	as	a	whole	convey	to	the	reader	that	the	team	has	the	software	development	
experience	necessary	in	order	to	carry	out	a	follow-up	contract?	i.e.,	that	if	the	team	were	assigned	
another	software	development	project	by	a	Client,	the	team	could	carry	it	out	as	successfully	as	they	
carried	out	this	one.
- [x] Although	 all	 bachelor	 projects	 are	 software	 development	 projects	 and	 follow	 a	 particular	
pattern,	in	the	end	every	project	has	a	unique	aspect	to	it.	Does	the	report	as	a	whole	communicate	
how	this	project	was	special?	Are	there	innovative	aspects	that	should	be	more	clearly	emphasized?
The	 report	 is	 the	 “official”	 record	 of	 the	 bachelor	 project	 and	 is	 published	 to	
http://repository.tudelft.nl.	Is	the	team	happy	that	the	report	adequately	represents	the	effort	that	
they	invested	into	the	project	and	the	solution	and	insights	that	they	achieved?

**Comment by landgenoot** [comment]
![20170623_123957](https://user-images.githubusercontent.com/2787511/27478994-2fb83814-5812-11e7-83c1-f9024258a8c2.jpg)
