### ISSUE TITLE
jMRTD with ECDSA to passport

### ISSUE THREAD

**Issue by klikooo** [digital-voting-pass/digital-voting-pass-app#21]
Communication between ePassport and Android device

Sign 8 byte array and retrieve public key from DG15

**Comment by landgenoot** [comment]
https://github.com/Glamdring/epassport-reader.git

**Comment by wkmeijer** [comment]
After some fiddeling the clone from epassport-reader works.

What the connection with the passport needs to do:
- read public key
- signing transactions

**Comment by wkmeijer** [comment]
Copied most of the epassport-reader app to an activity in digital-voting-pass-app. The activity can now be loaded when phone detects an NFC chip and can read and display data from it.

**Comment by wkmeijer** [comment]
Can read 1806 bits from DG15, but haven't succeeded in isolating the public key from that.
My passport has a 256 bit brainpoolP256r1 curve, so public key must be 32 byte?
http://www.passport.go.kr/img/download/vol2.pdf might be interesting to read futher

**Comment by wkmeijer** [comment]
App reads the correct data from DG15,
for passports <2014 this is 226 bytes
for passports >2014 this is 377 bytes

**Comment by wkmeijer** [comment]
App can now sign 8 bytes of data with the passport.
The passport returns 192 bytes of signed data. (not sure if this is the intended behavior, will look into it later) SignedData is different each time the same string is signed, which is a sign (pun not intended) the passport does actually sign the data, since the signing algorithm is non-deterministic.

**Comment by wkmeijer** [comment]
Writing tests for the connection with the passport will be a lot of work, since the inputstreams and data from the datagroups in the passport need to be mocked. Not sure if this is worth it.
