### ISSUE TITLE
Wireframe of voting station app

### ISSUE THREAD

**Issue by klikooo** [digital-voting-pass/digital-voting-pass-app#24]

**Comment by landgenoot** [comment]
https://marvelapp.com/39b062h

**Comment by landgenoot** [comment]
Some feedback for Angelo:

* "Bekijk transactiegeschiedenis" should be a real button
* Amount of votes should be displayed more prominent
* Transaction history should be listed in multiple cards
* Add activity where you can confirm the current active election. If none is active it shows when the polling stations will be opened
* After authorization, the should be two choices: 
    * Redeem vote
    * Cancel
* Redeem vote will show a quick confirmation and return to start
* The action bar in android is used for branding, navigation, search, and actions. Maybe use another way to show hints and process.

**Comment by jonathanraes** [comment]
Amount of votes moet gewoon bovenaan ergens staan meer prominent inderdaad,
Current active election should also be shown on starting screen,
End screen should show confirmation status, and change to "authorizatie voltooid" when confirmation is in
Button to "handmatige invoer" in NFC scan activity

**Comment by landgenoot** [comment]
![screenshot from 2017-05-22 11-32-20](https://cloud.githubusercontent.com/assets/2787511/26301764/6be9a9b0-3ee2-11e7-8a6c-ae2d9667fdb0.png)
May use this structure for the transaction history

**Comment by landgenoot** [comment]
Show app bar everywhere
Process notifications at bottom
