### ISSUE TITLE
Blockchain implementation - Blockchain identity

### ISSUE THREAD

**Issue by landgenoot** [digital-voting-pass/digital-voting-pass-app#3]
Access control system based on blockchain:
http://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=7163223

Biometric passport keypair
http://www.passport.go.kr/img/download/vol2.pdf

Signing data
https://github.com/andrew867/epassportviewer/blob/5425aef2300fc7f371f96c7d09ed0666e1cd8d28/pypassport-2.0/pypassport/iso7816.py

**Comment by jonathanraes** [comment]
[Proposed solution to decoupling of users' keys and identity](https://eprint.iacr.org/2017/110.pdf)
