### ISSUE TITLE
OCR activity crashes and won't start in special case

### ISSUE THREAD

**Issue by wkmeijer** [digital-voting-pass/digital-voting-pass-app#34]
When the OCR activity is open on landscape mode, then the screen is locked, and then the screen is unlocked again while phone is held in portrait mode. The OCR activity crashes and won't start-up without restarting the entire app.

**Comment by jonathanraes** [comment]
I cannot reproduce this bug

**Comment by wkmeijer** [comment]
After some better inspection I have come to the conclusion that the bug has nothing to do with screen rotation. It has to do with landscape mode, in landscape mode when locking and unlocking the screen, the activity crashes.

**Comment by wkmeijer** [comment]
[This stackoverflow](https://stackoverflow.com/questions/37723740/cordova-plugin-device-motion-exception-in-start-method) issue mentions a smilar issue. (although for different hardware) It gives the same kind of exception I get.

Because on other devices and emulators I can't reproduce this bug, I think it has to do with my device (HUAWEI P7L) and therefore I don't think this bug can be easily fixed or has a high priority to fix. I'll close the issue.
