### ISSUE TITLE
Black bar on OCR view

### ISSUE THREAD

**Issue by wkmeijer** [digital-voting-pass/digital-voting-pass-app#44]
There is a black bar on the bottom of the screen in OCR mode (portrait) and to the right (landscape). This causes the preview of the camera to not be fully visible.

**Comment by jonathanraes** [comment]
See Camera2BasicFragment:setUpCameraOutputs,                     
In the line, mTextureView.setAspectRatio(mPreviewSize.getHeight() + 150, mPreviewSize.getWidth()); (currently line 504)
The +150 here is hardcoded to minimalize the black bar
