### ISSUE TITLE
Test app's OCR related methods

### ISSUE THREAD

**Issue by jonathanraes** [digital-voting-pass/digital-voting-pass-app#49]

**Comment by jonathanraes** [comment]
TessBaseAPI cannot be instantiated in test environment -> UnsatisfiedlinkError

Starting threads in test gives errors on getLooper()
Creating a test Thread and passing it in the constructor works, but when job is posted on handler it doesnt seem to run

**Comment by wkmeijer** [comment]
Tried for a while to find another mrz traineddata file and tried for a while to fix the crash the current mrz.traineddata causes, but couldn't find any solutions.

Trying to create own traineddata via [this guide](http://pretius.com/how-to-prepare-training-files-for-tesseract-ocr-and-improve-characters-recognition/) and using [this boxeditor](http://vietocr.sourceforge.net/training.html).

Created traineddatafile from the ocr-b.ttf using [this website](http://trainyourtesseract.com), this gives the best results yet.
