### ISSUE TITLE
Risk analysis permissions

### ISSUE THREAD

**Issue by klikooo** [digital-voting-pass/digital-voting-pass-app#50]
Create a risk analysis for permissions

**Comment by klikooo** [comment]
`connect` – to connect to other nodes and see the blockchain’s contents.
`send` – to send funds, i.e. sign inputs of transactions.
`receive` – to receive funds, i.e. appear in the outputs of transactions.
`issue` – to issue assets, i.e. sign inputs of transactions which create new native assets.
`create` – to create streams, i.e. sign inputs of transactions which create new streams.
`mine` – to mine blocks, i.e. to sign the metadata of coinbase transactions.
`activate` – to change connect, send and receive permissions for other users, i.e. sign transactions which change those permissions.
`admin` – to change all permissions for other users, including issue, mine, activate and admin.

With `admin` right it is possible to revoke permissions of users. This is useful when a person dies just before an election and this person has an account on the blockchain with a token. The government is now able to revoke the permissions of this person, so no other person can 'steal' the token by proxy voting. 

A disadvantage of an admin account is that this account can be hacked, and can be used to tamper with the elections. This can be prevented by revoking the permissions of the admin (the admin can do this himself). The problem with this solution is that revoking the permissions of other nodes is not possible any more, so a solution to revoke proxy votes of dead persons should be thought of.

For the other permissions see #51

**Comment by wkmeijer** [comment]
I see that in #51 the reasons to give certain people permissions are explained. In the report it would be nice to write a short paragraph for each of the permission levels in the same style as `admin` is explained above.

**Comment by klikooo** [comment]
See report
