### ISSUE TITLE
Refactor MultiChain

### ISSUE THREAD

**Issue by klikooo** [digital-voting-pass/digital-voting-pass-app#53]
Fix some issues commented on commits
- [x] Fix shady signature size
- [x] Fix return true by checking signature encoding in `interpreter.cpp`
- [x] Only sign/verify transactions in four parts, so mine should be signed in one go

**Comment by klikooo** [comment]
Fix shady signature size is done, see [link](https://github.com/digital-voting-pass/digital-voting-pass-multichain/commit/511ed5826869676254aebe20c088e554fe470bcc)

**Comment by klikooo** [comment]
All are done, see https://github.com/digital-voting-pass/digital-voting-pass-multichain/commit/f79ceb74607c3a27c6a828a1ece44a47c35e12f7 and the next commit

Verify only transactions in four parts: https://github.com/digital-voting-pass/digital-voting-pass-multichain/tree/split-up-hash. In different because this must be tested with Java multichain

**Comment by wkmeijer** [comment]
A bit hard to understand for me what exactly changed with the workaround for the signature size, but the refactoring of the true statements seems like a good improvement. I'll take a look at the pull request.
