### ISSUE TITLE
UX implementation

### ISSUE THREAD

**Issue by klikooo** [digital-voting-pass/digital-voting-pass-app#55]

**Comment by wkmeijer** [comment]
- [x] Laad/openingscherm - Rico
- [x] Keuze verkiezing - Wilko
- [x] Mainactivity - Keuze OCR of handmatig - Wilko
- [x] OCR view - Jonathan
- [x] Handmatige invoer - Jonathan
- [x] Scan NFC - Wilko
- [x] Authorisatieformulier - Wilko
- [x] Transactiegeschiedenis - Wilko

**Comment by jonathanraes** [comment]
https://marvelapp.com/39b062h/screen/28342702

**Comment by wkmeijer** [comment]
For transaction history list: https://github.com/codepath/android_guides/wiki/Using-an-ArrayAdapter-with-ListView

**Comment by wkmeijer** [comment]
Split the classes into multiple packages, for a few classes I couldn't think of a right package. Please take a look at the [commit ](https://github.com/digital-voting-pass/digital-voting-pass-app/commit/dbb2877f9e00b9b459e18205a151851ce5777406)to see if you agree with the choice of packages.
