### ISSUE TITLE
Test app UI

### ISSUE THREAD

**Issue by klikooo** [digital-voting-pass/digital-voting-pass-app#60]

**Comment by wkmeijer** [comment]
Maybe [this solution](https://stackoverflow.com/questions/26065596/how-to-run-travis-ci-and-espresso-test) will fix the failing test on travis.

> If you receive an error like this
> `PerformException: Error performing 'single click' on view`
> Add this code to test:
> `closeSoftKeyboard();`
> `Thread.sleep(1000);`

**Comment by klikooo** [comment]
Got it to work see 8a60396edc9b4f2ae7bf8da2eb1ee60b64f63d76. The problem was that the button was not fully visible and the normal click functions requires at least 90% visibility.
