### ISSUE TITLE
White screen before splash screen

### ISSUE THREAD

**Issue by wkmeijer** [digital-voting-pass/digital-voting-pass-app#90]
Before the splash screen is loaded, a white screen is shown. I think this is the actual splash screen, so something must be broken. This is since the functionality of loading the blockchain in the app is added.

**Comment by jonathanraes** [comment]
Suggests the onCreate function takes a long time to execute, though this should not be the case..

**Comment by wkmeijer** [comment]
https://www.bignerdranch.com/blog/splash-screens-the-right-way/
