### ISSUE TITLE
Crash entering passport (nfc) connection activity

### ISSUE THREAD

**Issue by jonathanraes** [digital-voting-pass/digital-voting-pass-app#93]
java.lang.NoSuchFieldError: No static field id_sha3_224 of type Lorg/spongycastle/asn1/ASN1ObjectIdentifier; in class Lorg/spongycastle/asn1/nist/NISTObjectIdentifiers; or its superclasses (declaration of 'org.spongycastle.asn1.nist.NISTObjectIdentifiers' appears in /data/app/com.digitalvotingpass.digitalvotingpass-1/base.apk:classes9.dex)

Line 30 PassportConActivity

**Comment by wkmeijer** [comment]
Occurs since commit https://github.com/digital-voting-pass/digital-voting-pass-app/commit/748d9f91a15414df21424f517f651a59a53fe203

**Comment by wkmeijer** [comment]
Fixed on https://github.com/digital-voting-pass/digital-voting-pass-app/commit/5d80b55f004fa545d2eca0971e38156ef21d3297
