### ISSUE TITLE
Process SIG feedback

### ISSUE THREAD

**Issue by klikooo** [digital-voting-pass/digital-voting-pass-app#95]

**Comment by wkmeijer** [comment]
[Analyse]
De code van het systeem scoort 4 sterren op ons onderhoudbaarheidsmodel, wat betekent dat de code bovengemiddeld onderhoudbaar is. De hoogste score is niet behaald door een lagere score voor Unit Size.

Voor Unit Size wordt er gekeken naar het percentage code dat bovengemiddeld lang is. Het opsplitsen van dit soort methodes in kleinere stukken zorgt ervoor dat elk onderdeel makkelijker te begrijpen, te testen en daardoor eenvoudiger te onderhouden wordt. Binnen de langere methodes in dit systeem, zoals bijvoorbeeld de 'Camera2BasicFragment.setUpCameraOutputs'-methode, zijn aparte stukken functionaliteit te vinden welke ge-refactored kunnen worden naar aparte methodes. Commentaarregels zoals bijvoorbeeld 'Find out if we need to swap dimension to get the preview size relative to sensor coordinate' zijn een goede indicatie dat er een autonoom stuk functionaliteit te ontdekken is. Het is aan te raden kritisch te kijken naar de langere methodes binnen dit systeem en deze waar mogelijk op te splitsen.

In bovenstaand voorbeeld valt het overigens op dat het bestand "Copyright 2014 The Android Open Source Project" bevat. De packagenaam (com.digitalvotingpass.camera) is echter van jullie, dus het wekt de indruk dat jullie het oorspronkelijke bestand hebben aangepast. Ik heb dit daarom opzettelijk als voorbeeld genomen: als je er voor kiest om andermans code te adopteren en aan te passen, ben je vanaf nu ook verantwoordelijk voor het onderhoud van deze code.

De aanwezigheid van test-code is in ieder geval veelbelovend, hopelijk zal het volume van de test-code ook groeien op het moment dat er nieuwe functionaliteit toegevoegd wordt. 

Over het algemeen scoort de code bovengemiddeld, hopelijk lukt het om dit niveau te behouden tijdens de rest van de ontwikkelfase.

**Comment by jonathanraes** [comment]
#40

**Comment by wkmeijer** [comment]
#136
